#alis
.gitignore_global		Music
#alis
alias ll='ls -l'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

#Let mac ls has colors
export CLICOLOR=1
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx
# if use white bg use the line below instead
# export LSCOLORS=ExFxCxDxBxegedabagacad
